// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    var Client, ClientForm, ClientList, ClientListView, ClientView;
    Client = (function(_super) {

      __extends(Client, _super);

      function Client() {
        return Client.__super__.constructor.apply(this, arguments);
      }

      Client.prototype.defaults = {
        name: 'NYU',
        email: 'nyu@example.com',
        address: '5th Ave.'
      };

      return Client;

    })(Backbone.Model);
    ClientList = (function(_super) {

      __extends(ClientList, _super);

      function ClientList() {
        return ClientList.__super__.constructor.apply(this, arguments);
      }

      ClientList.prototype.model = Client;

      ClientList.prototype.initialize = function() {
        this.add(new Client({
          email: 'foo@example.com',
          name: 'Foo'
        }));
        this.add(new Client({
          email: 'bar@example.com',
          name: 'Bar'
        }));
        return this.add(new Client({
          email: 'baz@example.com',
          name: 'Baz'
        }));
      };

      return ClientList;

    })(Backbone.Collection);
    ClientView = (function(_super) {

      __extends(ClientView, _super);

      function ClientView() {
        this.render = __bind(this.render, this);
        return ClientView.__super__.constructor.apply(this, arguments);
      }

      ClientView.prototype.el = $("#content");

      ClientView.prototype.template = _.template($("#client-template").html());

      ClientView.prototype.render = function() {
        return $(this.el).append(this.template(this.model.toJSON()));
      };

      return ClientView;

    })(Backbone.View);
    ClientListView = (function(_super) {

      __extends(ClientListView, _super);

      function ClientListView() {
        this.render = __bind(this.render, this);
        return ClientListView.__super__.constructor.apply(this, arguments);
      }

      ClientListView.prototype.el = $('#content');

      ClientListView.prototype.url = '/clients';

      ClientListView.prototype.initialize = function() {
        this.collection = new ClientList();
        return this.render();
      };

      ClientListView.prototype.render = function() {
        var client, client_view, index, _ref;
        _ref = this.collection.models;
        for (index in _ref) {
          client = _ref[index];
          client_view = new ClientView({
            model: client
          });
          $(this.el).append(client_view.render().el);
        }
        return this;
      };

      return ClientListView;

    })(Backbone.View);
    ClientForm = (function(_super) {

      __extends(ClientForm, _super);

      function ClientForm() {
        this.render = __bind(this.render, this);
        return ClientForm.__super__.constructor.apply(this, arguments);
      }

      ClientForm.prototype.initialize = function() {
        this.client = new Client();
        return this.render();
      };

      ClientForm.prototype.el = $('#content');

      ClientForm.prototype.render = function() {
        $(this.el).html("<form id=\"client-form\" title=\"Add Client\" name=\"client-form\" action=\"\" method=\"GET\">\n  <input type=\"text\" id=\"client-name\" placeholder=\"Name\">\n  <input type=\"text\" id=\"client-email\" placeholder=\"Email address\">\n  <a class=\"whiteButton\" id=\"client-submit\">Save</a>\n</form>");
        return this;
      };

      ClientForm.prototype.events = {
        'click #client-submit': 'create'
      };

      ClientForm.prototype.create = function(event) {
        var client;
        event.preventDefault();
        client = {
          name: this.$('#client-name').val(),
          email: this.$('#client-email').val()
        };
        return this.collection.add(client);
      };

      return ClientForm;

    })(Backbone.View);
    return new ClientListView();
  });

}).call(this);
